[tool.poetry]
name = "auditorium"
version = "0.6.5"
description = "A Python-powered slideshow maker with steroids."
authors = ["Alejandro Piad <alepiad@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
markdown = "^3.1.1"
fire = "^0.2.1"
sanic = "^19.9.0"
jinja2 = "^2.10.3"
pygments = "^2.5.2"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
pytest-cov = "^2.8.1"
pylint = "^2.4.4"
matplotlib = "^3.1.2"
mypy = "^0.760"
mkdocs = "^1.0.4"

[tool.poetry.scripts]
auditorium = "auditorium.__main__:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

